title: Lyteforce Learns Github Pages
author: Lyteforce
email: lyteforce@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just the first page, of possibly many, that I'll have using Github Pages. I'm learning as I go along you see?
theme: minima

# social links
twitter_username: lyteforce # DO NOT include the @ character, or else the build will fail!
github_username:  lyteforce # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
